from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import anyio
from anthropic import Anthropic
from dotenv import load_dotenv
from openai import OpenAI

from .context import (
    build_web_search_trace,
    format_tooluniverse_context,
    format_web_context,
    render_pretty_web_trace,
    tooluniverse_context,
    web_search_context,
)
from .tooluniverse_mcp import (
    ANTHROPIC_TOOLUNIVERSE_TOOLS,
    OPENAI_TOOLUNIVERSE_TOOLS,
    TOOLUNIVERSE_SYSTEM_PROMPT,
    ToolUniverseMCPClient,
    render_pretty_tool_trace,
)
from .usage_costs import build_usage_metrics


DEFAULT_SYSTEM_PROMPT = (
    "You answer scientific experimental-design and research questions directly. "
    "Do not mention hidden reasoning. Be concise but complete, and use provided context when it is relevant. "
    "Prefer a compact, well-structured answer over an exhaustive essay."
)

DEFAULT_OUTPUT_TOKEN_BUDGET = 5000
RETRY_OUTPUT_TOKEN_BUDGET = 8000
MAX_TOOLUNIVERSE_TOOL_CALLS = 30
MAX_TOOLUNIVERSE_TRANSIENT_RETRIES = 2

# Anthropic adaptive-thinking. For Opus 4.7 the API expects
#   thinking={"type":"adaptive"} and output_config={"effort": "low"|"medium"|"high"}.
# Enabled by setting OPUS47_THINKING_EFFORT=low|medium|high. Unset -> off.
# Adaptive thinking is opaque from the caller's perspective: thinking tokens are
# rolled into output_tokens, no separate "thinking" content block is returned.
_THINKING_EFFORT = (os.environ.get("OPUS47_THINKING_EFFORT") or "").strip().lower()
if _THINKING_EFFORT and _THINKING_EFFORT not in ("low", "medium", "high"):
    raise ValueError(f"OPUS47_THINKING_EFFORT must be low|medium|high, got {_THINKING_EFFORT!r}")
THINKING_ELIGIBLE_MODELS = {"claude-opus-4-7"} if _THINKING_EFFORT else set()


def _anthropic_thinking_kwargs(model_name: str) -> dict[str, Any]:
    if model_name in THINKING_ELIGIBLE_MODELS:
        # `display: "summarized"` is required on Opus 4.7 to expose thinking
        # content. Without it the API defaults to `"omitted"`, which returns
        # thinking blocks with only a signature and no readable `thinking`
        # text. Anthropic's summary is generated by a separate summarizer
        # model and represents the gist of the full reasoning chain.
        return {
            "thinking": {"type": "adaptive", "display": "summarized"},
            "output_config": {"effort": _THINKING_EFFORT},
        }
    return {}


class GenerationFailure(RuntimeError):
    def __init__(self, message: str, *, raw_response: dict[str, Any] | None = None, tool_trace: list[dict[str, Any]] | None = None):
        super().__init__(message)
        self.raw_response = raw_response
        self.tool_trace = tool_trace or []


def _flatten_exception_messages(exc: BaseException) -> list[str]:
    nested = getattr(exc, "exceptions", None)
    if nested:
        messages: list[str] = []
        for item in nested:
            messages.extend(_flatten_exception_messages(item))
        return messages
    message = str(exc).strip() or exc.__class__.__name__
    return [f"{exc.__class__.__name__}: {message}"]


def _describe_exception(exc: BaseException) -> str:
    messages = _flatten_exception_messages(exc)
    unique_messages: list[str] = []
    for message in messages:
        if message not in unique_messages:
            unique_messages.append(message)
    return " | ".join(unique_messages)


def load_local_env(project_root: Path) -> None:
    load_dotenv(project_root / ".env", override=False)
    if not os.getenv("ANTHROPIC_API_KEY") and os.getenv("ANTROPIC_API_KEY"):
        os.environ["ANTHROPIC_API_KEY"] = os.environ["ANTROPIC_API_KEY"]


@dataclass(frozen=True)
class ModelSpec:
    provider: str
    model_name: str
    display_name: str


def default_model_specs() -> list[ModelSpec]:
    return [
        ModelSpec(provider="openai", model_name="gpt-5.4", display_name="gpt-5.4"),
        ModelSpec(provider="openai", model_name="gpt-5.5", display_name="gpt-5.5"),
        ModelSpec(provider="anthropic", model_name="claude-haiku-4-5", display_name="claude-haiku-4.5"),
        ModelSpec(provider="anthropic", model_name="claude-opus-4-7", display_name="claude-opus-4.7"),
        ModelSpec(provider="anthropic", model_name="claude-opus-4-6", display_name="claude-opus-4.6"),
        ModelSpec(provider="anthropic", model_name="claude-sonnet-4-6", display_name="claude-sonnet-4.6"),
    ]


def default_tiers() -> list[str]:
    return ["internal_only", "web_tools", "tooluniverse"]


def build_user_prompt(question: str, tier: str, context_text: str | None) -> str:
    lines = ["Question:", question.strip()]
    if tier != "internal_only" and context_text:
        lines.extend(["", context_text.strip(), "", "Use the context above when it helps, but do not rely on it blindly."])
    return "\n".join(lines)


class AnswerRunner:
    def __init__(self, project_root: Path):
        load_local_env(project_root)
        self.project_root = project_root
        self._openai_client: OpenAI | None = None
        self._anthropic_client: Anthropic | None = None

    @property
    def openai_client(self) -> OpenAI:
        if self._openai_client is None:
            self._openai_client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
        return self._openai_client

    @property
    def anthropic_client(self) -> Anthropic:
        if self._anthropic_client is None:
            self._anthropic_client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))
        return self._anthropic_client

    def gather_context(self, question: str, tier: str) -> dict[str, Any]:
        if tier == "internal_only":
            return {"type": tier, "text": None, "raw": None}
        if tier == "web_tools":
            payload = web_search_context(question)
            return {"type": tier, "text": format_web_context(payload), "raw": payload}
        if tier == "tooluniverse":
            payload = tooluniverse_context(question, cwd=self.project_root)
            return {"type": tier, "text": format_tooluniverse_context(payload), "raw": payload}
        raise ValueError(f"Unsupported tier: {tier}")

    def generate(self, model: ModelSpec, tier: str, question: str) -> dict[str, Any]:
        context_payload: dict[str, Any] = {"type": tier, "text": None, "raw": None}
        raw_response: dict[str, Any] | None = None
        trace: list[dict[str, Any]] = []
        web_trace: list[dict[str, Any]] = []
        try:
            if tier == "tooluniverse":
                context_payload = {
                    "type": tier,
                    "text": "ToolUniverse MCP tools are available at runtime.",
                    "raw": {"mode": "mcp_tool_calls", "transport": "stdio", "core_tools": [tool["name"] for tool in OPENAI_TOOLUNIVERSE_TOOLS]},
                }
                if model.provider == "openai":
                    text, raw_response, trace = self._generate_openai_tooluniverse(model.model_name, question)
                elif model.provider == "anthropic":
                    text, raw_response, trace = self._generate_anthropic_tooluniverse(model.model_name, question)
                else:
                    raise ValueError(f"Unsupported provider: {model.provider}")
            else:
                context_payload = self.gather_context(question, tier)
                user_prompt = build_user_prompt(question, tier, context_payload.get("text"))
                if tier == "web_tools":
                    web_trace = build_web_search_trace(context_payload.get("raw") or {}, context_payload.get("text") or "")
                if model.provider == "openai":
                    text, raw_response = self._generate_openai(model.model_name, user_prompt)
                elif model.provider == "anthropic":
                    text, raw_response = self._generate_anthropic(model.model_name, user_prompt)
                else:
                    raise ValueError(f"Unsupported provider: {model.provider}")
        except GenerationFailure as exc:  # pragma: no cover - depends on external APIs
            usage_metrics = build_usage_metrics(model.provider, model.model_name, exc.raw_response)
            return {
                "provider": model.provider,
                "model_name": model.model_name,
                "display_name": model.display_name,
                "tier": tier,
                "response_text": None,
                "error": str(exc),
                "context": context_payload,
                "raw_response": exc.raw_response,
                "tool_trace": exc.tool_trace,
                "web_trace": web_trace,
                "usage_metrics": usage_metrics,
            }
        except Exception as exc:  # pragma: no cover - depends on external APIs
            return {
                "provider": model.provider,
                "model_name": model.model_name,
                "display_name": model.display_name,
                "tier": tier,
                "response_text": None,
                "error": str(exc),
                "context": context_payload,
                "raw_response": None,
                "tool_trace": [],
                "web_trace": [],
                "usage_metrics": None,
            }

        if tier == "web_tools":
            raw_response = {
                **raw_response,
                "pretty_web_trace": render_pretty_web_trace(web_trace),
            }
        else:
            web_trace = []

        usage_metrics = build_usage_metrics(model.provider, model.model_name, raw_response)
        return {
            "provider": model.provider,
            "model_name": model.model_name,
            "display_name": model.display_name,
            "tier": tier,
            "response_text": text,
            "error": None,
            "context": context_payload,
            "raw_response": raw_response,
            "tool_trace": trace,
            "web_trace": web_trace,
            "usage_metrics": usage_metrics,
        }

    def _generate_openai(self, model_name: str, user_prompt: str) -> tuple[str, dict[str, Any]]:
        attempts: list[dict[str, Any]] = []
        last_text = ""
        for budget in (DEFAULT_OUTPUT_TOKEN_BUDGET, RETRY_OUTPUT_TOKEN_BUDGET):
            response = self.openai_client.responses.create(
                model=model_name,
                input=[
                    {"role": "system", "content": DEFAULT_SYSTEM_PROMPT},
                    {"role": "user", "content": user_prompt},
                ],
                max_output_tokens=budget,
            )
            raw = response.model_dump(mode="json")
            attempts.append({"max_output_tokens": budget, "response": raw})
            last_text = response.output_text
            if not self._openai_response_incomplete(raw):
                return last_text, {"attempts": attempts, "final": raw}

        raise GenerationFailure(
            "OpenAI response was truncated after retrying with a larger token budget.",
            raw_response={"attempts": attempts, "final": attempts[-1]["response"] if attempts else None},
        )

    def _generate_anthropic(self, model_name: str, user_prompt: str) -> tuple[str, dict[str, Any]]:
        attempts: list[dict[str, Any]] = []
        last_text = ""
        thinking_kwargs = _anthropic_thinking_kwargs(model_name)
        for budget in (DEFAULT_OUTPUT_TOKEN_BUDGET, RETRY_OUTPUT_TOKEN_BUDGET):
            response = self.anthropic_client.messages.create(
                model=model_name,
                system=DEFAULT_SYSTEM_PROMPT,
                max_tokens=budget,
                messages=[{"role": "user", "content": user_prompt}],
                **thinking_kwargs,
            )
            raw = response.model_dump(mode="json")
            attempts.append({"max_tokens": budget, "response": raw})
            parts = []
            for block in response.content:
                if getattr(block, "type", None) == "text":
                    parts.append(block.text)
            last_text = "".join(parts)
            if not self._anthropic_response_incomplete(raw):
                return last_text, {"attempts": attempts, "final": raw}

        raise GenerationFailure(
            "Anthropic response was truncated after retrying with a larger token budget.",
            raw_response={"attempts": attempts, "final": attempts[-1]["response"] if attempts else None},
        )

    @staticmethod
    def _openai_response_incomplete(raw: dict[str, Any]) -> bool:
        if raw.get("status") == "incomplete":
            return True
        return bool(raw.get("incomplete_details"))

    @staticmethod
    def _anthropic_response_incomplete(raw: dict[str, Any]) -> bool:
        return raw.get("stop_reason") == "max_tokens"

    def _generate_openai_tooluniverse(self, model_name: str, question: str) -> tuple[str, dict[str, Any], list[dict[str, Any]]]:
        return anyio.run(self._generate_openai_tooluniverse_async, model_name, question)

    async def _generate_openai_tooluniverse_async(self, model_name: str, question: str) -> tuple[str, dict[str, Any], list[dict[str, Any]]]:
        raw_turns: list[dict[str, Any]] = []
        trace_events: list[dict[str, Any]] = []
        execute_tool_calls = 0

        try:
            async with ToolUniverseMCPClient(self.project_root) as tool_client:
                response = self.openai_client.responses.create(
                model=model_name,
                input=[
                    {"role": "system", "content": TOOLUNIVERSE_SYSTEM_PROMPT},
                    {"role": "user", "content": question.strip()},
                ],
                tools=OPENAI_TOOLUNIVERSE_TOOLS,
                tool_choice="required",
                max_output_tokens=DEFAULT_OUTPUT_TOKEN_BUDGET,
            )
                raw_turns.append(response.model_dump(mode="json"))

                while True:
                    current_raw = raw_turns[-1]
                    tool_calls = [item for item in response.output if getattr(item, "type", None) == "function_call"]
                    if tool_calls:
                        outputs = []
                        for tool_call in tool_calls:
                            args = json.loads(tool_call.arguments or "{}")
                            execution = await tool_client.execute_model_tool(tool_call.name, args)
                            trace_events.append(execution.trace_event)
                            if execution.trace_event["mcp_tool_name"] == "execute_tool" and execution.trace_event["ok"]:
                                execute_tool_calls += 1
                            outputs.append(
                                {
                                    "type": "function_call_output",
                                    "call_id": tool_call.call_id,
                                    "output": json.dumps(execution.model_result, ensure_ascii=True),
                                }
                            )
                        if len(trace_events) > MAX_TOOLUNIVERSE_TOOL_CALLS:
                            raise GenerationFailure(
                                "Exceeded maximum ToolUniverse tool calls in OpenAI tool loop.",
                                raw_response={"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)},
                                tool_trace=trace_events,
                            )
                        response = self.openai_client.responses.create(
                            model=model_name,
                            previous_response_id=response.id,
                            input=outputs,
                            tools=OPENAI_TOOLUNIVERSE_TOOLS,
                            max_output_tokens=DEFAULT_OUTPUT_TOKEN_BUDGET,
                        )
                        raw_turns.append(response.model_dump(mode="json"))
                        continue

                    if execute_tool_calls == 0:
                        response = self.openai_client.responses.create(
                            model=model_name,
                            previous_response_id=response.id,
                            input=[
                                {
                                    "role": "user",
                                    "content": "You must use tooluniverse_execute_tool at least once to gather real ToolUniverse data before finalizing your answer.",
                                }
                            ],
                            tools=OPENAI_TOOLUNIVERSE_TOOLS,
                            tool_choice="required",
                            max_output_tokens=DEFAULT_OUTPUT_TOKEN_BUDGET,
                        )
                        raw_turns.append(response.model_dump(mode="json"))
                        continue

                    if self._openai_response_incomplete(current_raw):
                        raise GenerationFailure(
                            "OpenAI ToolUniverse answer was truncated.",
                            raw_response={"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)},
                            tool_trace=trace_events,
                        )
                    return response.output_text, {"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)}, trace_events
        except GenerationFailure:
            raise
        except Exception as exc:
            raise GenerationFailure(
                str(exc),
                raw_response={"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)} if raw_turns else None,
                tool_trace=trace_events,
            ) from exc

    def _generate_anthropic_tooluniverse(self, model_name: str, question: str) -> tuple[str, dict[str, Any], list[dict[str, Any]]]:
        last_failure: GenerationFailure | None = None
        for attempt in range(MAX_TOOLUNIVERSE_TRANSIENT_RETRIES + 1):
            try:
                return anyio.run(self._generate_anthropic_tooluniverse_async, model_name, question)
            except GenerationFailure as exc:
                last_failure = exc
                if attempt >= MAX_TOOLUNIVERSE_TRANSIENT_RETRIES or not self._is_retryable_tooluniverse_failure(exc):
                    raise
        assert last_failure is not None
        raise last_failure

    @staticmethod
    def _is_retryable_tooluniverse_failure(exc: GenerationFailure) -> bool:
        message = str(exc).lower()
        retry_markers = [
            "taskgroup",
            "brokenresourceerror",
            "closedresourceerror",
            "endofstream",
            "broken pipe",
            "connection reset",
            "connection aborted",
            "streamclosed",
        ]
        return any(marker in message for marker in retry_markers)

    async def _generate_anthropic_tooluniverse_async(self, model_name: str, question: str) -> tuple[str, dict[str, Any], list[dict[str, Any]]]:
        raw_turns: list[dict[str, Any]] = []
        trace_events: list[dict[str, Any]] = []
        execute_tool_calls = 0
        messages: list[dict[str, Any]] = [{"role": "user", "content": question.strip()}]
        thinking_kwargs = _anthropic_thinking_kwargs(model_name)
        thinking_on = bool(thinking_kwargs)
        # Anthropic rejects tool_choice={"type":"any"} when extended thinking is enabled;
        # fall back to "auto" (the only supported choice with thinking + tools).
        any_choice: dict[str, Any] = {"type": "auto"} if thinking_on else {"type": "any"}
        tool_choice: dict[str, Any] | None = any_choice
        tools_enabled = True
        forced_execute_reminder_sent = False
        forced_finalize_sent = False
        final_answer_retry_used = False

        try:
            async with ToolUniverseMCPClient(self.project_root) as tool_client:
                while True:
                    max_tokens = RETRY_OUTPUT_TOKEN_BUDGET if (forced_finalize_sent or final_answer_retry_used) else DEFAULT_OUTPUT_TOKEN_BUDGET
                    request_kwargs: dict[str, Any] = {
                        "model": model_name,
                        "system": TOOLUNIVERSE_SYSTEM_PROMPT,
                        "max_tokens": max_tokens,
                        "messages": messages,
                        **thinking_kwargs,
                    }
                    if tools_enabled:
                        request_kwargs["tools"] = ANTHROPIC_TOOLUNIVERSE_TOOLS
                        if tool_choice is not None:
                            request_kwargs["tool_choice"] = tool_choice
                    response = self.anthropic_client.messages.create(**request_kwargs)
                    current_raw = response.model_dump(mode="json")
                    raw_turns.append(current_raw)

                    tool_uses = [block for block in response.content if getattr(block, "type", None) == "tool_use"]
                    if tool_uses:
                        messages.append({"role": "assistant", "content": current_raw["content"]})
                        tool_results = []
                        for block in tool_uses:
                            args = dict(block.input)
                            execution = await tool_client.execute_model_tool(block.name, args)
                            trace_events.append(execution.trace_event)
                            if execution.trace_event["mcp_tool_name"] == "execute_tool" and execution.trace_event["ok"]:
                                execute_tool_calls += 1
                            tool_results.append(
                                {
                                    "type": "tool_result",
                                    "tool_use_id": block.id,
                                    "content": json.dumps(execution.model_result, ensure_ascii=True),
                                }
                            )
                        messages.append({"role": "user", "content": tool_results})

                        if len(trace_events) >= MAX_TOOLUNIVERSE_TOOL_CALLS and execute_tool_calls > 0:
                            messages.append(
                                {
                                    "role": "user",
                                    "content": "You already have enough ToolUniverse evidence. Do not call more tools. Write the final answer now.",
                                }
                            )
                            tools_enabled = False
                            tool_choice = None
                            forced_finalize_sent = True
                            continue

                        if len(trace_events) >= 12 and execute_tool_calls == 0 and not forced_execute_reminder_sent:
                            messages.append(
                                {
                                    "role": "user",
                                    "content": (
                                        "Stop tool discovery. On the next tool step, call tooluniverse_execute_tool exactly once with concrete arguments for a real data source, "
                                        "for example PubMed_search_articles with a query about elephant TP53, or an NCBI/Ensembl gene lookup for TP53 in elephant. After that, finalize the answer."
                                    ),
                                }
                            )
                            forced_execute_reminder_sent = True
                            tool_choice = any_choice
                            continue

                        if len(trace_events) > MAX_TOOLUNIVERSE_TOOL_CALLS:
                            raise GenerationFailure(
                                "Exceeded maximum ToolUniverse tool calls in Anthropic tool loop.",
                                raw_response={"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)},
                                tool_trace=trace_events,
                            )

                        tool_choice = {"type": "auto"}
                        continue

                    if execute_tool_calls == 0:
                        messages.append({"role": "assistant", "content": current_raw["content"]})
                        messages.append(
                            {
                                "role": "user",
                                "content": "You must use tooluniverse_execute_tool at least once to gather real ToolUniverse data before finalizing your answer.",
                            }
                        )
                        tool_choice = any_choice
                        tools_enabled = True
                        continue

                    if forced_finalize_sent:
                        text_parts = [block.text for block in response.content if getattr(block, "type", None) == "text"]
                        return "".join(text_parts), {"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)}, trace_events

                    if self._anthropic_response_incomplete(current_raw):
                        if not final_answer_retry_used:
                            messages.append({"role": "assistant", "content": current_raw["content"]})
                            messages.append(
                                {
                                    "role": "user",
                                    "content": "Continue exactly where you left off and finish the answer. Do not call any more tools.",
                                }
                            )
                            tools_enabled = False
                            tool_choice = None
                            forced_finalize_sent = True
                            final_answer_retry_used = True
                            continue
                        raise GenerationFailure(
                            "Anthropic ToolUniverse answer was truncated after retrying with a larger token budget.",
                            raw_response={"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)},
                            tool_trace=trace_events,
                        )

                    text_parts = [block.text for block in response.content if getattr(block, "type", None) == "text"]
                    return "".join(text_parts), {"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)}, trace_events
        except GenerationFailure:
            raise
        except Exception as exc:
            raise GenerationFailure(
                _describe_exception(exc),
                raw_response={"turns": raw_turns, "pretty_tool_trace": render_pretty_tool_trace(trace_events)} if raw_turns else None,
                tool_trace=trace_events,
            ) from exc
